<a href="https://colab.research.google.com/github/GBakalkinOAI/DDLS2024/blob/main/Module%201%20lab%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello, World!")

Hello, World!


In [12]:
import numpy as np

arr = np.arange(5)
arr **= 2
print(arr)

[ 0  1  4  9 16]


In [13]:
arr.reshape((5,1))

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16]])

In [14]:
arr.sum()

30

In [16]:
arr *= 3
print(arr)

[ 0  3 12 27 48]


In [17]:
!pip install torch

In [18]:
import torch